ALTER SEQUENCE cities_id_seq RESTART WITH 3580;
ALTER SEQUENCE states_id_seq RESTART WITH 55;
ALTER SEQUENCE unit_photos_id_seq RESTART WITH 311422;
ALTER SEQUENCE units_id_seq RESTART WITH 33905;
ALTER SEQUENCE users_id_seq RESTART WITH 2504;

