ALTER SEQUENCE cities_id_seq RESTART WITH 2980;
ALTER SEQUENCE states_id_seq RESTART WITH 54;
ALTER SEQUENCE unit_photos_id_seq RESTART WITH 264323;
ALTER SEQUENCE units_id_seq RESTART WITH 29825;
ALTER SEQUENCE users_id_seq RESTART WITH 2607;

